name: flutter_hooks_gallery
description: A new Flutter project.

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_collection: any
  built_value: any
  flutter:
    sdk: flutter
  flutter_hooks:
    path: ../
  http: ^0.13.4
  provider: ^4.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: any
  built_value_generator: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
